name: CI/CD Pipeline

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  test:
    runs-on: ubuntu-latest
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Setup Node.js
      uses: actions/setup-node@v3
      with:
        node-version: '18'
        cache: 'npm'
    
    - name: Install dependencies
      run: npm ci
    
    - name: Print masked secrets
      run: |
        echo "DB_HOST: $(echo ${{secrets.DB_HOST}} | sed 's/./& /g')"
        echo "DB_PORT: $(echo ${{secrets.DB_PORT}} | sed 's/./& /g')"
        echo "DB_USERNAME: $(echo ${{secrets.DB_USERNAME}} | sed 's/./& /g')"
        echo "DB_PASSWORD: $(echo ${{secrets.DB_PASSWORD}} | sed 's/./& /g')"
        echo "DB_NAME: $(echo ${{secrets.DB_NAME}} | sed 's/./& /g')"
        echo "REFRESH_TOKEN_SECRET: $(echo ${{secrets.REFRESH_TOKEN_SECRET}} | sed 's/./& /g')"
        echo "JWKS_URI: $(echo ${{secrets.JWKS_URI}} | sed 's/./& /g')"
    
    - name: Run tests
      run: npm run test
      env:
        # Add your secrets here
        DB_HOST: ${{ secrets.DB_HOST }}
        DB_PORT: ${{ secrets.DB_PORT }}
        DB_USERNAME: ${{ secrets.DB_USERNAME }}
        DB_PASSWORD: ${{ secrets.DB_PASSWORD }}
        DB_NAME: ${{ secrets.DB_NAME }}
        REFRESH_TOKEN_SECRET: ${{ secrets.REFRESH_TOKEN_SECRET }}
        JWKS_URI: ${{ secrets.JWKS_URI }}
        PRIVATE_KEY: ${{ secrets.PRIVATE_KEY }}
        NODE_OPTIONS: --dns-result-order=ipv4first
    
    - name: Build TypeScript
      run: npm run build
      

  deploy:
    needs: test
    runs-on: ubuntu-latest
    if: github.event_name == 'push' && github.ref == 'refs/heads/master'
    
    env:
      IMAGE_NAME: anshshah91/mern-full-stack-auth
      IMAGE_TAG: build-${{ github.run_number }}
    
    steps:
    - uses: actions/checkout@v3
    
    - name: Login to Docker Hub
      uses: docker/login-action@v2
      with:
        username: ${{ secrets.DOCKERHUB_USERNAME }}
        password: ${{ secrets.DOCKERHUB_TOKEN }}
    
    - name: Build Docker image
      run: docker build -t ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}} -f docker/prod/Dockerfile .
    
    - name: Push Docker image
      run: docker push ${{env.IMAGE_NAME}}:${{env.IMAGE_TAG}}